Parameters:
  channelaccesstokenParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: channel-access-token
  channelsecretParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: channel-secret
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  lambdaServiceRole494E4CA6:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: DrugManegementAppStack/lambda/ServiceRole/Resource
  lambdaServiceRoleDefaultPolicyBF6FA5E7:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:Scan
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - MedicationHistoryADC1A6AB
                  - Arn
              - Fn::GetAtt:
                  - Medications0A1EF4C5
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - MedicationHistoryADC1A6AB
                        - Arn
                    - /index/*
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: lambdaServiceRoleDefaultPolicyBF6FA5E7
      Roles:
        - Ref: lambdaServiceRole494E4CA6
    Metadata:
      aws:cdk:path: DrugManegementAppStack/lambda/ServiceRole/DefaultPolicy/Resource
  lambda8B5974B5:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 2d8ffe70a4c14e4dd1f7ec2899dea68afbd26b8ece5eed61e9d6bccbad0c8770.zip
      Environment:
        Variables:
          CHANNEL_ACCESS_TOKEN:
            Ref: channelaccesstokenParameter
          CHANNEL_SECRET:
            Ref: channelsecretParameter
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - lambdaServiceRole494E4CA6
          - Arn
      Runtime: nodejs20.x
    DependsOn:
      - lambdaServiceRoleDefaultPolicyBF6FA5E7
      - lambdaServiceRole494E4CA6
    Metadata:
      aws:cdk:path: DrugManegementAppStack/lambda/Resource
      aws:asset:path: C:\git\drug-manegement-app\cdk.out\asset.2d8ffe70a4c14e4dd1f7ec2899dea68afbd26b8ece5eed61e9d6bccbad0c8770
      aws:asset:is-bundled: true
      aws:asset:property: Code
  lambdaFunctionUrl327AA8ED:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn:
        Fn::GetAtt:
          - lambda8B5974B5
          - Arn
    Metadata:
      aws:cdk:path: DrugManegementAppStack/lambda/FunctionUrl/Resource
  lambdainvokefunctionurl8987155C:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName:
        Fn::GetAtt:
          - lambda8B5974B5
          - Arn
      FunctionUrlAuthType: NONE
      Principal: "*"
    Metadata:
      aws:cdk:path: DrugManegementAppStack/lambda/invoke-function-url
  LineBotApi541032A3:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: LineBotApi
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/Resource
  LineBotApiDeployment23FEF956e89aacbef6658130c65b8ca832009533:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: LineBotApi541032A3
    DependsOn:
      - LineBotApiproxyANYBB58D256
      - LineBotApiproxy748B7A04
      - LineBotApiANY5868A3CB
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/Deployment/Resource
  LineBotApiDeploymentStageprod510D3E32:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: LineBotApiDeployment23FEF956e89aacbef6658130c65b8ca832009533
      RestApiId:
        Ref: LineBotApi541032A3
      StageName: prod
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/DeploymentStage.prod/Resource
  LineBotApiproxy748B7A04:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - LineBotApi541032A3
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: LineBotApi541032A3
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/Default/{proxy+}/Resource
  LineBotApiproxyANYApiPermissionDrugManegementAppStackLineBotApi8A0390E3ANYproxy3D641FA9:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - lambda8B5974B5
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: LineBotApi541032A3
            - /
            - Ref: LineBotApiDeploymentStageprod510D3E32
            - /*/*
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/Default/{proxy+}/ANY/ApiPermission.DrugManegementAppStackLineBotApi8A0390E3.ANY..{proxy+}
  LineBotApiproxyANYApiPermissionTestDrugManegementAppStackLineBotApi8A0390E3ANYproxy99141A87:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - lambda8B5974B5
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: LineBotApi541032A3
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/Default/{proxy+}/ANY/ApiPermission.Test.DrugManegementAppStackLineBotApi8A0390E3.ANY..{proxy+}
  LineBotApiproxyANYBB58D256:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - lambda8B5974B5
                  - Arn
              - /invocations
      ResourceId:
        Ref: LineBotApiproxy748B7A04
      RestApiId:
        Ref: LineBotApi541032A3
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/Default/{proxy+}/ANY/Resource
  LineBotApiANYApiPermissionDrugManegementAppStackLineBotApi8A0390E3ANY5E8C2AC5:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - lambda8B5974B5
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: LineBotApi541032A3
            - /
            - Ref: LineBotApiDeploymentStageprod510D3E32
            - /*/
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/Default/ANY/ApiPermission.DrugManegementAppStackLineBotApi8A0390E3.ANY..
  LineBotApiANYApiPermissionTestDrugManegementAppStackLineBotApi8A0390E3ANYF39D4356:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - lambda8B5974B5
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: LineBotApi541032A3
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/Default/ANY/ApiPermission.Test.DrugManegementAppStackLineBotApi8A0390E3.ANY..
  LineBotApiANY5868A3CB:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - lambda8B5974B5
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - LineBotApi541032A3
          - RootResourceId
      RestApiId:
        Ref: LineBotApi541032A3
    Metadata:
      aws:cdk:path: DrugManegementAppStack/LineBotApi/Default/ANY/Resource
  Medications0A1EF4C5:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: medicationId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: medicationId
          KeyType: RANGE
      TableName: Medications
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: DrugManegementAppStack/Medications/Resource
  MedicationHistoryADC1A6AB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: historyId
          AttributeType: S
        - AttributeName: takenTime
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: MedicationHistoryByTakenTime
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: takenTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: historyId
          KeyType: HASH
        - AttributeName: takenTime
          KeyType: RANGE
      TableName: MedicationHistory
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: DrugManegementAppStack/MedicationHistory/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/81V32/aMBD+W+rHyc1ou4epb7RjExqlDOjDFCF0xEcwdezIdtpGVv73yXYC6bpu1fYyCZT47vzddz9znpx9HCSDE3g0pxm7PxV8k7iFheyeXm/lDDQUaFHTORpV6QxT8o7Q9r+i8GjWTkCxYbCWiuHeJNPw+FzJzHIlU0dQWl2Ty3BnB5IJ1O1JV9LyAtsTygeulSxQ2laSKRaVDXXx99dgzYpyKBI3VwJTR8CYqkB2VZNLR0rNZcZLEMMsU9XBe7TxF4YhlJYJKUBCjmymBM84GnKZumeyeqhb25VnDIwt1axzES38nVZrLWS7sRRc4kHnU/tn5eu4K186T5xGcahZB7dUXvPCy0sxYwsLFn0KTY/wL8TBX3TVUHOxBmPQmmToH9RcJFdVdo/2CgymKxq7JXHXW9k1Ce1e7rRIHdm2p64Old0t69JXdno7HZHo7k6L4BV1wY3hSjYUSp6DxUeoEzcJXuZo7LDkqSMMt1AJO5YWcw099H4T+fienWMiIwj9hKVQtY874JlM87JPs+RdJ6IFLo/m5gAeajZROc9AjNmzpL5dHkgd0enCQo6BUifqkQ/Kw/CGEoTBnWn1VB9m2pES9HHuXk1Wq7hBu1PsNkR/DK4H0XKPdl1PdckMLmnUpY7oVtLVw9qyuxcE/AUL9ZPjf0QIvOKFhrJaQqHYJnFL2Ig2M5Z7868YtoWEw5KxsSsXfisYpe3vLawHnB51Gy4El/lNXHKz4ff1bDRfz0ff7kaLZWijQj0cJ9u3nNWq7nL9/5ECxr4ItQGxwExJBroeS4ZPYUFy/9bz88YASq32GJZBuwGGkwnpZiBUqGlo2DO+0bnMvfy2smVlG+o/SMnevH84HyRnH5LByd5wftp+J5J5fP4Ak2xwvQAHAAA=
    Metadata:
      aws:cdk:path: DrugManegementAppStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  LineBotApiEndpoint96ACF474:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: LineBotApi541032A3
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: LineBotApiDeploymentStageprod510D3E32
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-3
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-3
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-4
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
      - Fn::Equals:
          - Ref: AWS::Region
          - us-west-2

